server:
  port: 8999

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: MLB-PLAYER-SERVICE
          uri: lb://MLB-PLAYER-SERVICE
          predicates:
            - Path=/players/**
        - id: MLB-TEAM-SERVICE
          uri: lb://MLB-TEAM-SERVICE
          predicates:
            - Path=/teams/**
        - id: NBA-PLAYER-SERVICE
          uri: lb://NBA-PLAYER-SERVICE
          predicates:
            - Path=/players/**
        - id: NBA-TEAM-SERVICE
          uri: lb://NBA-TEAM-SERVICE
          predicates:
            - Path=/teams/**
        - id: NFL-PLAYER-SERVICE
          uri: lb://NFL-PLAYER-SERVICE
          predicates:
            - Path=/players/**
        - id: NFL-TEAM-SERVICE
          uri: lb://NFL-TEAM-SERVICE
          predicates:
            - Path=/teams/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka/
    instance:
      hostname: localhost